### ISSUE TITLE
I am getting an econnrefused error...

### ISSUE THREAD

**Issue by dmsmith111** [luisiam/homebridge-liftmaster2#13]
The error is:

errorhub { Error: connect ECONNREFUSED 10.0.1.8:5222
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.1.8',
  port: 5222 }

**Comment by luisiam** [comment]
Are you constantly getting this error? A full log will be appreciated.

**Comment by dmsmith111** [comment]
Where do I get the log from?  Yes, I get the error all of the time.  Thanks for the quick response.

**Comment by luisiam** [comment]
Some other program is using the port 5222 and homebridge try to use that port as well. I don't think it's related to the liftmaster plugin.

**Comment by dmsmith111** [comment]
I actually fixed it by changing the main Homebridge port.  So, it is no longer throwing that error.  Now, I have two garage door openers on my system and it is throwing an error about multiple devices with the same ID.  How do I handle multiple garage doors?

**Comment by luisiam** [comment]
Can you post your config.json?

**Comment by dmsmith111** [comment]
Here is the config.json file I was using...

**Comment by luisiam** [comment]
Cannot see anything from your comment

**Comment by dmsmith111** [comment]
[config.json.zip](https://github.com/luisiam/homebridge-liftmaster2/files/679775/config.json.zip)

**Comment by dmsmith111** [comment]
[config.json-2.zip](https://github.com/luisiam/homebridge-liftmaster2/files/679776/config.json-2.zip)

**Comment by dmsmith111** [comment]
[config.json-3.zip](https://github.com/luisiam/homebridge-liftmaster2/files/679778/config.json-3.zip)

**Comment by luisiam** [comment]
Can you post the error log as well?
