### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by rchoughton** [luisiam/homebridge-liftmaster2#20]
I had this working for several weeks and overnight I started getting the following error. Any idea what is causing it.  I removed the liftmaster from the config.json file and homebridge with smartthings is working fine. 

Loaded plugin: homebridge-liftmaster2
Registering platform 'homebridge-liftmaster2.LiftMaster2'
---
Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'
---
Loaded config.json with 0 accessories and 2 platforms.
---
Loading 2 platforms...
[SmartThings] Initializing SmartThings platform...
[SmartThings] Fetching Smart Things devices.
Initializing LiftMaster2 platform...
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br>
^
SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at Request._callback (/usr/lib/node_modules/homebridge-liftmaster2/index.js:186:21)
at Request.self.callback (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/reque
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules/request
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-liftmaster2/node_modules
at IncomingMessage.g (events.js:291:16)

**Comment by luisiam** [comment]
#18
