### ISSUE TITLE
Request Rejected + chokes on html error page when expecting JSON

### ISSUE THREAD

**Issue by sejmann** [luisiam/homebridge-liftmaster2#22]
I'm trying to troubleshoot this error that I've gotten for a few weeks.  Prior to this error, it worked fine for like a year.  I can log in successfully with the same credentials from the webapp from the same IP, so it's I'm not 'blacklisted' entirely, possibly just for the API.

The error originally occurred while using the original homebridge-liftmaster plugin, so I upgraded to this one.  I deleted my myQ account and recreated a new one, and I stil get this error.  I tried renaming my "Garage Door Opener" to "Garage Door" inside the app, as recommended by some long obsolete advice on the net, to no avail. 

Because the "Request Rejected" HTML is returned when JSON is expected, the parser chokes.  Because this isn't trapped or caught, it puts homebridge in a crash-restart loop.  Also, because it's processed in a callback, it's not immediately obvious to me which URL is failing, but I presume its the initial login.

Any idea what triggers a request to be denied?  Power went out to my garage one day.  Maybe homebride misbehaved and attempted repeated logins past some threshold?  I guess I'll try to force my cable company to assign a new IP to my modem.  

UPDATE: I managed to get my IP to change, and I'm still getting rejected, so it doesn't appear to be that.

```[2/23/2017, 12:22:22 AM] Loaded plugin: homebridge-liftmaster2
[2/23/2017, 12:22:22 AM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[2/23/2017, 12:22:22 AM] ---
[2/23/2017, 12:22:22 AM] Loaded config.json with 12 accessories and 1 platforms.
[2/23/2017, 12:22:22 AM] ---
[2/23/2017, 12:22:22 AM] Loading 1 platforms...
[2/23/2017, 12:22:22 AM] Initializing LiftMaster2 platform...
[2/23/2017, 12:22:22 AM] Loading 12 accessories...
...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │XXX-XX-XXX │
    └────────────┘

[2/23/2017, 12:22:23 AM] Homebridge is running on port 51826.
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[XXXX59538945582XXXX]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/opt/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
    at Request.self.callback (/opt/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
sejmann@mbp15-wired:~$```

**Comment by welizer** [comment]
I am also having the same issue.  Based on my research I have found out that LiftMaster changed the API in the past few weeks and this is the cause of the issue.  My Alexa skill for the same garage doors failed at the same time.  I have since been able to update the code for Alexa to deal with the new API and it works fine.

**Comment by luisiam** [comment]
This was reported in #18 and it's fixed with the latest version.

**Comment by welizer** [comment]
Fantastic!  Thanks. I will try it out asap.

**Comment by sejmann** [comment]
Okay, it was (mostly) my fault.  I was upgrading the plugin via 
`sudo npm install -g homebridge-liftmaster2`
instead of
`sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git`
assuming npmjs had the latest version, which it didn't.
