### ISSUE TITLE
Request Rejected

### ISSUE THREAD

**Issue by paxinos** [luisiam/homebridge-liftmaster2#23]
This error started recently...

undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389623889293]</body></html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)

**Comment by luisiam** [comment]
Reported in issue #18 
Please update to the latest version
