### ISSUE TITLE
MyQ HTML causing exception/crash

### ISSUE THREAD

**Issue by craig-miller** [luisiam/homebridge-liftmaster2#24]
The following happens when starting homebridge.  Did a fresh sudo npm remove -g homebridge-liftmaster2 and homebridge, then reinstalled.  

config.json follows the stdout section.

Looks like something changed on the MyQ side of things.

stdout:
```
[4/4/2017, 11:33:22 AM] Loaded plugin: homebridge-liftmaster2
[4/4/2017, 11:33:22 AM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[4/4/2017, 11:33:22 AM] ---
[4/4/2017, 11:33:22 AM] Loaded config.json with 0 accessories and 1 platforms.
[4/4/2017, 11:33:22 AM] ---
[4/4/2017, 11:33:22 AM] Loading 1 platforms...
[4/4/2017, 11:33:22 AM] Initializing LiftMaster2 platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ REDACTED │
    └────────────┘

[4/4/2017, 11:33:22 AM] Homebridge is running on port 51826.
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595390864034645]</body></html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
```

-----
$ cat .homebridge/config.json
```    
    {
        "bridge": {
            "name": "Homebridge",
            "username": "REDACTED",
            "port": 51826,
            "pin": "REDACTED"
        },

       "description": "Config file for Homebridge",
       "platforms": [{
            "platform": "LiftMaster2",
            "username": "REDACTED",
            "password": "REDACTED"
        }]
    }
```

**Comment by luisiam** [comment]
Please install with `npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git`

**Comment by craig-miller** [comment]
Thank you for the quick reply.  Yes, that worked.

**Comment by jagpreetbatth** [comment]
cannot download??
addRemoteGit git+https://github.com/luisiam/homebridge-liftmaster2.git resetting remote /Users/jagpreetbatth/.npm/_git-remotes/git-https-github-com-luisiam-homebridge-liftmaster2-git-354ff2dc because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
