### ISSUE TITLE
ideas appreciated

### ISSUE THREAD

**Issue by dishguy** [luisiam/homebridge-liftmaster2#34]
liftmaster2 version 0.4.3 works great on MacBook running home bridge... but when I try to run it on raspberry pi zero W, I get the error below... removed it from Pi and reinstalled it and get same error... removed it from Mac and reinstalled it on pi same error... reinstalled it on Mac runs perfectly.... I'm missing something... any suggestions?? would love to get the last item working to utilize the pi as my low power bridge and free up my Mac... there is a closed thread regarding this however nothing suggested there has helped me.... also i should mention after the plugin is installed it shows @0.1.0
it doesnt show 4.3

this is what I get on my Pi zero running node 8.x.x#

<title>Request Rejected</title>Your request has been denied.

[4251746506392562070] ^
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse ()
at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
at emitTwo (events.js:125:13)
at Request.emit (events.js:213:7)
at Request. (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1163:10)
at emitOne (events.js:115:13)
at Request.emit (events.js:210:7)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1085:12)
at Object.onceWrapper (events.js:314:30)

**Comment by kfalvin** [comment]
I'm having the same error, but its on my iMac.  Its not a problem with the JSON as far as I can tell (very much a novice).  I can't tell if this is an error being returned from using the username and password.

**Comment by dishguy** [comment]
User name or password will tell you specifically if that’s at fault

**Comment by iRayanKhan** [comment]
Can you paste your config please?
