### ISSUE TITLE
Can't Install 

### ISSUE THREAD

**Issue by alow11** [luisiam/homebridge-liftmaster2#36]
I am going to apologize in advance, I am new to this. I am running home bridge on a raspberry pi and have been able to get Nest and WeMo working but I can't seem to get this installed. 

Does this work on a raspberry pi? If so, why do I keep getting permission errors when installing?

Thanks in advance for anyone that helps!

**Comment by byronavory** [comment]
Can Not install on clean raspbian system, with prerequisites installed. 

Appears to be related ti issue with PCAP dependency.

pi@homebridge:/boot $ sudo npm install -g homebridge-amazondash
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-fd482b66': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-03T17_03_24_302Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-amazondash' ]
2 info using npm@6.5.0
3 info using node@v8.11.1
4 verbose npm-session 873cda5fe0d263d0
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-amazondash 2454ms (from cache)
8 silly pacote tag manifest for homebridge-amazondash@latest fetched in 2846ms
9 timing stage:loadCurrentTree Completed in 6602ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 10ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 60ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-amazondash@0.0.8 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/node-dash-button 855ms (from cache)
18 silly pacote range manifest for node-dash-button@^0.6.1 fetched in 981ms
19 silly resolveWithNewModule node-dash-button@0.6.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/underscore 867ms (from cache)
21 silly pacote range manifest for underscore@^1.8.3 fetched in 977ms
22 silly resolveWithNewModule underscore@1.9.1 checking installable status
**23 silly fetchPackageMetaData error for pcap@git+https://github.com/mranney/node_pcap.git Command failed: /usr/bin/git submodule update -q --init --recursive**
23 silly fetchPackageMetaData fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-fd482b66': Permission denied
24 timing stage:rollbackFailedOptional Completed in 30ms
25 timing stage:runTopLevelLifecycles Completed in 16690ms
26 verbose stack Error: Command failed: /usr/bin/git submodule update -q --init --recursive
26 verbose stack fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-fd482b66': Permission denied
26 verbose stack
26 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
26 verbose stack     at emitTwo (events.js:126:13)
26 verbose stack     at ChildProcess.emit (events.js:214:7)
26 verbose stack     at maybeClose (internal/child_process.js:925:16)
26 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
26 verbose stack     at emitOne (events.js:116:13)
26 verbose stack     at Socket.emit (events.js:211:7)
26 verbose stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
27 verbose cwd /boot
28 verbose Linux 4.14.79+
29 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-amazondash"
30 verbose node v8.11.1
31 verbose npm  v6.5.0
32 error code 128
33 error Command failed: /usr/bin/git submodule update -q --init --recursive
33 error fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-fd482b66': Permission denied
34 verbose exit [ 1, true ]
