### ISSUE TITLE
Unable to install Homebridge-Liftmaster2

### ISSUE THREAD

**Issue by HunterBFontenot** [luisiam/homebridge-liftmaster2#44]
I am attempting to install the latest version of the homebridge-liftmaster2 plugin and I keep getting stuck at the same point. Has anyone else experinced something simliar?

```
pi@homebridge:~ $ sudo npm install -g --unsafe-perm git+https://github.com/luisiam/homebridge-liftmaster2.git
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-87127408': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-17T17_04_07_039Z-debug.log

```

**Comment by HunterBFontenot** [comment]
Here is the output from the error log: 

```
pi@homebridge:/usr/lib/node_modules $ sudo tail -n 100  /root/.npm/_logs/2018-07-17T18_01_50_969Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '-save',
1 verbose cli   'git+https://github.com/luisiam/homebridge-liftmaster2.git' ]
2 info using npm@6.2.0
3 info using node@v8.11.3
4 verbose npm-session fb72f3ab899018ea
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/luisiam/homebridge-liftmaster2.git Command failed: /usr/bin/git submodule update -q --init --recursive
7 silly fetchPackageMetaData fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-108d97cf': Permission denied
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 4178ms
10 verbose stack Error: Command failed: /usr/bin/git submodule update -q --init --recursive
10 verbose stack fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-108d97cf': Permission denied
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
10 verbose stack     at emitTwo (events.js:126:13)
10 verbose stack     at ChildProcess.emit (events.js:214:7)
10 verbose stack     at maybeClose (internal/child_process.js:925:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
11 verbose cwd /usr/lib/node_modules
12 verbose Linux 4.14.52-v7+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "-save" "git+https://github.com/luisiam/homebridge-liftmaster2.git"
14 verbose node v8.11.3
15 verbose npm  v6.2.0
16 error code 128
17 error Command failed: /usr/bin/git submodule update -q --init --recursive
17 error fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-108d97cf': Permission denied
18 verbose exit [ 1, true ]
```

**Comment by nmelanson75** [comment]
I have the same issue, where you able to get this resolved?

**Comment by HunterBFontenot** [comment]
Someone on Reddit helped me work through it. Here is the thread:

https://www.reddit.com/r/homebridge/comments/8zh2fv/is_anyone_able_to_get_the_chamberlin_liftmaster/?st=JKITNLCJ&sh=e09a2d70

**Comment by iRayanKhan** [comment]
Resolved, please close.
