### ISSUE TITLE
Device keeps being re-added to configuration

### ISSUE THREAD

**Issue by jamesg311** [luisiam/homebridge-liftmaster2#57]
Every time Homekit/Homebridge polls the state of my Garage door, I see in the logs that the device is being "added" again. I have tried multiple different config changes in the JSON including adding the Gateway ID but when I do that, it no longer recognizes the device. Copying my current config below.

Log message:
[1/13/2019, 9:25:09 PM] [LiftMaster2] Adding Device: "Garage" - Device ID: 4445501 (Gateway: "undefined" - Gateway ID: 4445502)

Config (with credentials hidden):
{
            "platform": "LiftMaster2",
            "username": "***",
            "password": "***",
            "openDuration": 15,
            "closeDuration": 25,
            "polling": true,
            "longPoll": 300,
            "shortPoll": 5,
            "shortPollDuration": 120
        },

**Comment by eightnoneone** [comment]
Same here. Just started using, so I'm unsure if this is new/different behavior.

**Comment by dpyy** [comment]
Does it actually operate? Mine doesnt even operate with this error

**Comment by Robhof** [comment]
As long as I don’t restart homebridge it works.

**Comment by gfungsynergygateway** [comment]
Any fix to this issue? Mine used to work with this error, but now it doesnt

**Comment by nicholasrobinson** [comment]
I am hitting this issue...

As @Robhof mentions, it does not cause a problem unless you restart Homebridge. After restarting, I encounter:
```
(node:378) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 531fbbd9-e574-45db-91e6-f654c6041a97
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:198:13)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:171:8)
    at /homebridge/node_modules/homebridge-liftmaster2/index.js:334:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The work-around is to:
- Remove the `"platform": "LiftMaster2",` block from Homebridge's config.json. 
- Restart Homebridge. 
- Re-add the `"platform": "LiftMaster2",` block in Homebridge's config.json. 
- Restart Homebridge
